# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 224e319e31ba2b216901934eccd280d7f7acfe981b8c7f6426d5d9004401d2037893b1dd79ed6b21db23c645227e80bcb0fcb53d762e3c5e4703a568d4b7eb2d

test:
  secret_key_base: de867fe54f04771b969e7a9a8a877f6c2db8dae1025ddff6499aa16e36e15f9327e276d679e78f7abca1edfc5e3866622b99b782c39f461bb61be8593472b923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
